name: third workflow
on: push

jobs:
  run-third-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: list
      run: ls -la
    #- name: use ready
    #  uses: actions/checkout@v4
    - name: manual mode
      run: |
        git init
        git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
        git fetch origin
        git checkout main
    - name: list again
      run: ls -la
